name: telegram bot Deploy

on:
  push:
    branches: [main]
    tags:
      - "v*"

env:
  BOT_IMAGE: ${{ secrets.BOT_IMAGE }}
  DOCKER_NETWORK: ${{ secrets.DOCKER_NETWORK }}

jobs:
  build-Bot:
    runs-on: ubuntu-latest
    outputs:
      imagetag: ${{ steps.image_tag.outputs.imagetag }}
    steps:
      - uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tag, labels)
        id: meta
        uses: docker/metadata-action@v5.9.0
        with:
          images: ${{env.BOT_IMAGE}}
          tags: |
            type=semver,pattern={{version}}
            type=sha,format=long
            type=raw,value=latest
            

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy bot (first tag only)
        id: image_tag
        run: |
          # Get first tag from metadata (split by newline)
          FIRST_TAG=$(echo "${{ steps.meta.outputs.tag-names }}" | head -n1)
          if [ -z "$FIRST_TAG" ]; then
            echo "No tag found, exiting."
            exit 1
          fi
          echo "Deploying tag: $FIRST_TAG"
          echo "imagetag=$FIRST_TAG" >> $GITHUB_OUTPUT

  deploy-bot:
    needs: 
      - build-Bot
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: BOT_IMAGE
          script: |
          
            IMAGE=${BOT_IMAGE}:${{ needs.build-Bot.outputs.imagetag }}
            sudo docker pull $IMAGE
            sudo docker stop exambot || true
            sudo docker rm exambot || true

            sudo docker run -d \
            --name exambot \
            --env-file /home/ubuntu/deploy/.tele_bot.env \
            --network ${{ secrets.DOCKER_NETWORK}} \
            --network-alias bot \
            -p 4444:4444 \
            $IMAGE

            sudo docker system prune -f
